import {
  FaBootstrap,
  FaCss3Alt,
  FaGitAlt,
  FaGithub,
  FaHtml5,
  FaNodeJs,
  FaReact,
  FaShieldAlt,
  FaWix,
  FaWordpress,
} from "react-icons/fa";
import { IoLogoJavascript } from "react-icons/io5";
import {
  SiCanva,
  SiExpress,
  SiI18Next,
  SiMongodb,
  SiMui,
  SiSass,
  SiTypescript,
  SiJsonwebtokens,
  SiTailwindcss,
  SiWebstorm,
  SiCsharp,
  SiAdobe,
  SiNvm,
  SiPostman,
} from "react-icons/si";
import { RiNextjsFill, RiNpmjsFill } from "react-icons/ri";
import { GrValidate } from "react-icons/gr";
import { BsCheck2Circle } from "react-icons/bs";
import { TbCodeDots } from "react-icons/tb";
import { FcEngineering } from "react-icons/fc";
import { VscVscodeInsiders } from "react-icons/vsc";
import { HiMail } from "react-icons/hi";

export const TechstackList = [
  {
    _id: 1,
    title: "tech.programLng.title",
    list: [
      {
        _id: 1,
        name: "HTML",
        icon: FaHtml5,
        color: "#e34f27",
        description: "tech.programLng.description.html",
        url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
      },
      {
        _id: 2,
        name: "CSS",
        icon: FaCss3Alt,
        color: "#1572b6",
        description: "tech.programLng.description.css",
        url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
      },
      {
        _id: 3,
        name: "JavaScript",
        icon: IoLogoJavascript,
        color: "#f7df1e",
        description: "tech.description.js",
        url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
      },
      {
        _id: 4,
        name: "TypeScript",
        icon: SiTypescript,
        color: "#3178c6",
        description: "tech.programLng.description.tsx",
        url: "https://www.typescriptlang.org",
      },
      {
        _id: 5,
        name: "JSON",
        icon: TbCodeDots,
        color: "#f0c52b",
        description: "tech.programLng.description.json",
        url: "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON#no_really_what_is_json",
      },
      {
        _id: 6,
        name: "C#",
        icon: SiCsharp,
        color: "#68217a",
        description: "tech.programLng.description.csharp",
        url: "https://docs.microsoft.com/en-us/dotnet/csharp",
      },
    ],
  },
  {
    _id: 2,
    title: "tech.fe.title",
    list: [
      {
        _id: 1,
        name: "Sass",
        icon: SiSass,
        color: "#cc6699",
        description: "tech.fe.description.sass",
        url: "https://sass-lang.com",
      },
      {
        _id: 2,
        name: "Bootstrap",
        icon: FaBootstrap,
        color: "#563d7c",
        description: "tech.fe.description.bootstrap",
        url: "https://getbootstrap.com",
      },
      {
        _id: 3,
        name: "React",
        icon: FaReact,
        color: "#61dafb",
        description: "tech.fe.description.react",
        url: "https://react.dev",
      },
      {
        _id: 4,
        name: "Next.js",
        icon: RiNextjsFill,
        color: "#000000",
        description: "tech.fe.description.nextjs",
        url: "https://nextjs.org",
      },
      {
        _id: 5,
        name: "MUI",
        icon: SiMui,
        color: "#007fff",
        description: "tech.fe.description.mui",
        url: "https://mui.com",
      },
      {
        _id: 6,
        name: "i18n",
        icon: SiI18Next,
        color: "#ff5722",
        description: "tech.fe.description.i18n",
        url: "https://www.i18next.com",
      },
      {
        _id: 7,
        name: "Yup",
        icon: BsCheck2Circle,
        color: "#4B8BBE",
        description: "tech.fe.description.yup",
        url: "https://www.npmjs.com/package/yup",
      },
      {
        _id: 8,
        name: "EJS",
        icon: FcEngineering,
        color: "#7B7B7B",
        description: "tech.fe.description.ejs",
        url: "https://ejs.co",
      },
      {
        _id: 9,
        name: "ValidatorJS",
        icon: GrValidate,
        color: "#F24E1E",
        description: "tech.fe.description.validatorjs",
        url: "https://www.npmjs.com/package/validatorjs",
      },
      {
        _id: 10,
        name: "JWT",
        icon: SiJsonwebtokens,
        color: "#F7DF1E",
        description: "tech.fe.description.jwt",
        url: "https://jwt.io",
      },
      {
        _id: 11,
        name: "Tailwind CSS",
        icon: SiTailwindcss,
        color: "#06B6D4",
        description: "tech.fe.description.tailwind",
        url: "https://tailwindcss.com",
      },
      {
        _id: 12,
        name: "Helmet",
        icon: FaShieldAlt,
        color: "#f5b041",
        description: "tech.fe.description.helmet",
        url: "https://helmetjs.github.io",
      },
    ],
  },
  {
    _id: 3,
    title: "tech.be.title",
    list: [
      {
        _id: 1,
        name: "NodeJs",
        icon: FaNodeJs,
        color: "#339933",
        description: "tech.be.description.nodejs",
        url: "https://nodejs.org",
      },
      {
        _id: 2,
        name: "Express",
        icon: SiExpress,
        color: "#000000",
        description: "tech.be.description.express",
        url: "https://expressjs.com",
      },
      {
        _id: 3,
        name: "MongoDB",
        icon: SiMongodb,
        color: "#47a248",
        description: "tech.be.description.mongodb",
        url: "https://www.mongodb.com",
      },
      {
        _id: 4,
        name: "Nodemailer",
        icon: TbCodeDots,
        color: "#007acc",
        description: "tech.be.description.nodemailer",
        url: "https://nodemailer.com",
      },
    ],
  },
  {
    _id: 4,
    title: "tech.versCont.title",
    list: [
      {
        _id: 1,
        name: "Git",
        icon: FaGitAlt,
        color: "#f05033",
        description: "tech.versCont.description.git",
        url: "https://git-scm.com",
      },
      {
        _id: 2,
        name: "Github",
        icon: FaGithub,
        color: "#181717",
        description: "tech.versCont.description.github",
        url: "https://github.com",
      },
    ],
  },
  {
    _id: 5,
    title: "tech.creation.title",
    list: [
      {
        _id: 1,
        name: "Canva",
        icon: SiCanva,
        color: "#00c4cc",
        description: "tech.creation.description.canva",
        url: "https://www.canva.com",
      },
      {
        _id: 2,
        name: "Adobe",
        icon: SiAdobe,
        color: "#ff0000",
        description: "tech.creation.description.adobe",
        url: "https://www.adobe.com/it/express",
      },
    ],
  },
  {
    _id: 6,
    title: "tech.builder.title",
    list: [
      {
        _id: 1,
        name: "Wix",
        icon: FaWix,
        color: "#000000",
        description: "tech.builder.description.wix",
        url: "https://it.wix.com",
      },
      {
        _id: 2,
        name: "WordPress",
        icon: FaWordpress,
        color: "#21759b",
        description: "tech.builder.description.wordpress",
        url: "https://wordpress.com",
      },
    ],
  },
  {
    _id: 7,
    title: "tech.editor.title",
    list: [
      {
        _id: 26,
        name: "Visual Studio Code",
        icon: VscVscodeInsiders,
        color: "#007ACC",
        description: "tech.editor.description.vscode",
        url: "https://code.visualstudio.com",
      },
      {
        _id: 27,
        name: "WebStorm",
        icon: SiWebstorm,
        color: "#000000",
        description: "tech.editor.description.webstorm",
        url: "https://www.jetbrains.com/webstorm",
      },
    ],
  },
  {
    _id: 8,
    title: "tech.devTools.title",
    list: [
      {
        _id: 1,
        name: "nvm",
        icon: SiNvm,
        color: "#4CAF50",
        description: "tech.devTools.description.nvm",
        url: "https://github.com/nvm-sh/nvm",
      },
      {
        _id: 2,
        name: "npm",
        icon: RiNpmjsFill,
        color: "#cb3837",
        description: "tech.devTools.description.npm",
        url: "https://www.npmjs.com",
      },
      {
        _id: 3,
        name: "Postman",
        icon: SiPostman,
        color: "#FF6C37",
        description: "tech.devTools.description.postman",
        url: "https://www.postman.com",
      },
      {
        _id: 4,
        name: "Mailgen",
        icon: HiMail,
        color: "#3498db",
        description: "tech.devTools.description.mailgen",
        url: "https://www.npmjs.com/package/mailgen",
      },
    ],
  },
];
